VIDEO_PORT = 5005  #
VIDEO_HOST = 'localhost'

VIDEO_SERVER_ADDRESS = (VIDEO_HOST, VIDEO_PORT)

AUDIO_PORT = 5006
AUDIO_HOST = 'localhost'

AUDIO_SERVER_ADDRESS = (AUDIO_HOST, AUDIO_PORT)

PAYLOAD_MAX_LEN = 1300

TYPE_AUDIO = 'Audio'
TYPE_VIDEO = 'Video'

AUDIO_FRAME_RATE = 44000
AUDIO_BUFFER_SIZE = 4400
